site_name: Alphaus Documentation
copyright: Copyright &copy; 2025 Alphaus Cloud. All rights reserved.

theme:
  name: material
  logo: assets/alphaus.png
  favicon: assets/alphaus.png
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - "General":
      - "index.md"
      - "products.md"
      - "IAM overview": "iam.md"
      - "Wave (Pro) ↗": "https://labs.alphaus.cloud/wavedocs-ja/"
      - "System status ↗": "https://status.alphaus.cloud/"
      - "API Reference (non-Blue)":
          - "apiref/index.md"
          - "apiref/endpoint-limits.md"
          - "apiref/authentication.md"
          - "apiref/users.md"
          - "apiref/api-clients.md"
          - "apiref/authorization.md"
          - "apiref/status.md"
  - "Ripple":
      - "ripple/index.md"
      - "ripple/concepts.md"
      - "A primer on TrueUnblended": "ripple/trueunblended.md"
      - "Knowledgebase ↗": "https://help.alphaus.cloud/en/"
      - "API Reference (non-Blue)":
          - "ripple/apiref/index.md"
          - "ripple/apiref/user.md"
          - "ripple/apiref/exchangerate.md"
          - "ripple/apiref/billinggroup.md"
          - "ripple/apiref/account.md"
          - "ripple/apiref/reseller.md"
          - "ripple/apiref/original-cost.md"
          - "ripple/apiref/ri-management.md"
          - "ripple/apiref/recalculation.md"
          - "ripple/apiref/invoice.md"
          - "ripple/apiref/export.md"
          - "ripple/apiref/project.md"
  - "Octo":
      - "Getting Started": "octo/index.md"
      - "Account Registration":
          - "Overview": "octo/accountregistration/account-registration.md"
          - "AWS":
            - "Registration": "octo/accountregistration/AWS/account-registration-aws.md"
            - "CloudFormation Templates":
              - "API Access": "octo/accountregistration/AWS/cloudformationtemplate/api-access.md"
              - "CUR and S3 Bucket": "octo/accountregistration/AWS/cloudformationtemplate/cur-s3-bucket-setup.md"
          - "Microsoft Azure CSP": "octo/accountregistration/account-registration-azure.md"
          - "Google Cloud": "octo/accountregistration/account-registration-gcp.md"
      - "octo/account-registration-gcpbigquery.md"
      - "Cost Groups":
          - "Overview": "octo/costgroup.md"
          - "AI Cost": "octo/aicost.md"
          - "Container Cost": "octo/container-cost.md"
      - "Reports":
          - "Overview": "octo/reports/overview.md"
          - "Fixed Report": "octo/reports/fixed-report.md"
          - "Custom Report": "octo/reports/custom-report.md"
      - "Recommendation":
          - "octo/recommendations/about.md"
          - "AWS Generated Recommendations":
              - "octo/recommendations/costexplorer.md"
              - "octo/recommendations/costoptimizationhub.md"
              - "octo/recommendations/trustedadvisor.md"
          - "GCP Generated Recommendations":
              - "octo/recommendations/recommendationhub.md"
          - "OCTO Generated Recommendations":
              - "octo/recommendations/octo/aws.md"
          - "octo/recommendations/executerecommendation.md"
      # - "octo/unitcost.md"
      - "Unit Economics":
          - "octo/uniteconomics/unitmetrics.md"
      - "Cost Allocation":
          - "octo/costallocation.md"
      - "Financial Planning":
          - "octo/budget.md"
          - "octo/forecasting.md"
      - "Alerts":
          - "octo/channel-management.md"
          - "octo/alerts-management.md"
      - "General Settings":
          - "octo/preferences.md"
          - "octo/user-management.md"
          - "octo/samlsso.md"
  - "Blue API":
      - "blueapi/overview.md"
      - "blueapi/authentication.md"
      - "CLI: bluectl": "blueapi/bluectl.md"
      - "blueapi/client-sdks.md"
  - "Guides":
      - "guides/index.md"
      - "Registering AWS payer accounts": "guides/aws-register-payer.md"
      - "Enabling AWS payer API access": "guides/aws-enable-api-access.md"
      - "guides/aws-query-costs.md"
      - "Scheduling invoice calculations": "guides/invoice-calc-sched.md"
      - "guides/aws-cost-mods.md"
  - "Blog": "https://labs.alphaus.cloud/blog/"

extra:
  alternate:
    - name: English
      link: /docs/
      lang: en
    - name: 日本語
      link: /docs-ja/
      lang: ja
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/alphaus/
    - icon: fontawesome/brands/github
      link: https://github.com/alphauslabs

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - footnotes
